apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-low
  namespace: notifications
spec:
  scaleTargetRef:
    name: worker-low
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 300
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: "__QUEUE_URL_LOW__"
        queueLength: "5"
        awsRegion: "__AWS_REGION__"
        identityOwner: operator
