name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: SQS Terraform Init
        working-directory: sqs
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=state/notification-sqs/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}"

      - name: SQS Terraform Apply
        working-directory: sqs
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_SQS_NAME: ${{ vars.QUEUE_NAME }}
        run: terraform apply -auto-approve

      - name: Build Go Binary
        run: |
          cd functions/end-point
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap .
          zip function.zip bootstrap

      - name: Terraform Init
        working-directory: functions/end-point
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=state/notification-publisher/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}"

      - name: Terraform Apply
        working-directory: functions/end-point
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_state_bucket: ${{ secrets.TF_STATE_BUCKET }}
          TF_VAR_lambda_role_arn: ${{ secrets.LAMBDA_ROLE_ARN }}
          TF_VAR_function-name: notification-publisher
          TF_VAR_SQS_NAME: ${{ vars.QUEUE_NAME }}
        run: terraform apply -auto-approve