name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      sqs: ${{ steps.filter.outputs.sqs }}
      function: ${{ steps.filter.outputs.function }}
      sqs-trigger: ${{ steps.filter.outputs.sqs-trigger }}
      sqs-alarm: ${{ steps.filter.outputs.sqs-alarm }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Changed Paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            sqs:
              - 'sqs/**'
            function:
              - 'functions/end-point/**'
            sqs-trigger:
              - 'functions/sqs-trigger/**'
            sqs-alarm:
              - 'cloud-watch-alarm/start-worker/**'

  deploy:
    needs: changes
    if: needs.changes.outputs.sqs == 'true' || needs.changes.outputs.function == 'true' || needs.changes.outputs.sqs-trigger == 'true' || needs.changes.outputs.sqs-alarm == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        if: needs.changes.outputs.function == 'true' || needs.changes.outputs.sqs-trigger == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: SQS Terraform Init
        if: needs.changes.outputs.sqs == 'true'
        working-directory: sqs
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=state/notification-sqs/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}"

      - name: SQS Terraform Apply
        if: needs.changes.outputs.sqs == 'true'
        working-directory: sqs
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_SQS_NAME: ${{ vars.QUEUE_NAME }}
        run: terraform apply -auto-approve

      - name: SQS trigger
        if: needs.changes.outputs.sqs-trigger == 'true'
        run: |
          cd functions/sqs-trigger
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap .
          zip function.zip bootstrap

      - name: SQS trigger Terraform Init
        if: needs.changes.outputs.sqs-trigger == 'true'
        working-directory: functions/sqs-trigger
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=state/sqs-trigger/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \

      - name: SQS trigger Terraform Apply
        if: needs.changes.outputs.sqs-trigger == 'true'
        working-directory: functions/sqs-trigger
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_state_bucket: ${{ secrets.TF_STATE_BUCKET }}
          TF_VAR_lambda_role_arn: ${{ secrets.LAMBDA_ROLE_ARN }}
          TF_VAR_function-name: sqs-trigger
        run: terraform apply -auto-approve

      - name: End point
        if: needs.changes.outputs.function == 'true'
        run: |
          cd functions/end-point
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap .
          zip function.zip bootstrap

      - name: End point Terraform Init
        if: needs.changes.outputs.function == 'true'
        working-directory: functions/end-point
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=state/notification-publisher/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \

      - name: End point Terraform Apply
        if: needs.changes.outputs.function == 'true'
        working-directory: functions/end-point
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_state_bucket: ${{ secrets.TF_STATE_BUCKET }}
          TF_VAR_lambda_role_arn: ${{ secrets.LAMBDA_ROLE_ARN }}
          TF_VAR_function-name: notification-publisher
          TF_VAR_SQS_NAME: ${{ vars.QUEUE_NAME }}
        run: terraform apply -auto-approve

      - name: Infra Alarm Terraform Init
        if: needs.changes.outputs.sqs-alarm == 'true'
        working-directory: cloud-watch-alarm/start-worker
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=state/sqs-alarm/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}"

      - name: Infra Alarm Terraform Apply
        if: needs.changes.outputs.sqs-alarm == 'true'
        working-directory: cloud-watch-alarm/start-worker
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_function_name: sqs-trigger
          TF_VAR_sqs_queue: ${{ vars.QUEUE_NAME }}
        run: terraform apply -auto-approve
